### ISSUE TITLE
Icorrect memory free for GNUTLS_VERSION_NUMBER < 0x030506

### ISSUE THREAD

**Issue by tangobear** [hfiref0x/LightFTP#12]
Hello

double free memory of addr ...
in function TLSCleanup() / gnutls_dh_params_deinit();
I try  fix in TLSInit()
...
gnutls_dh_params_deinit(dh_params); 
**dh_params = NULL**;  
...

**Comment by UldisRinkevichs** [comment]
Thank you for report.
