### ISSUE TITLE
hello,I want to install LightFTP on Ubuntu14.04 LTS, but there are some errors. 

### ISSUE THREAD

**Issue by lijunqiang123** [hfiref0x/LightFTP#18]
![image](https://user-images.githubusercontent.com/22146584/90732570-e1231f00-e2fd-11ea-9555-926f1d6c5d14.png)

**Comment by lijunqiang123** [comment]
Can you help me?Thank you.

**Comment by hfiref0x** [comment]
Hello,

try install the following packages

libhogweed/libhogweed4
