### ISSUE TITLE
Exit messages?

### ISSUE THREAD

**Issue by luiztheblues** [hfiref0x/LightFTP#21]
How could i add a custom exit message instead of the "Goodbye!" one?
Is there something undocumented on the configuration file or i need to do some hacks in the code?

**Comment by hfiref0x** [comment]
Go to https://github.com/hfiref0x/LightFTP/blob/a33e7a2a1ef3971cb5bacfbf97ea75aa3561ee78/Source/ftpserv.h#L175 and change it on whatever you want.

**Comment by luiztheblues** [comment]
Thanks a lot!
Sorry for bothering, i should've searched in code for myself.
