### ISSUE TITLE
How could i setup FTPS on LightFTP (if it supports it)?

### ISSUE THREAD

**Issue by takusuman** [hfiref0x/LightFTP#22]
How could i do it?
I didn't found much documentation about it.

**Comment by UldisRinkevichs** [comment]
You need to add or modify following configuration entries in your .conf file:
ServerCertificate=<full path+filename to your certificate file>
Keyfile=<full path+filename to your .pem private key file>
KeyfilePassword=<plaintext password to .pem>

You can generate keys and self-signed certificates using OpenSSL or supply already existing ones from a certificate authorities
