### ISSUE TITLE
issue with commands working with files

### ISSUE THREAD

**Issue by behnamben** [hfiref0x/LightFTP#23]
I tried to use file-related commands like LIST or RETR or STOR, but they would return: "150 File status okay; about to open data connection. 451 Requested action aborted. Local error in processing."
Is there something wrong?

**Comment by UldisRinkevichs** [comment]
Hi! Can you post here details about your command sequence that produces error? Also try to check your configuration files for errors in local file system path and its availability for ftp process user.

**Comment by behnamben** [comment]
For example:

USER ubuntu
PASS ubuntu
LIST

would always give me the error 
150 File status okay; about to open data connection.
451 Requested action aborted. Local error in processing.

The user ubuntu has the admin access and the OS ufw is disabled.

**Comment by UldisRinkevichs** [comment]
Are you trying to use FTP by hand with telnet-like client or your custom software?
The PASV/PORT command must precede LIST/RETR/STOR/MLSD commands to create a second data channel they use.

https://datatracker.ietf.org/doc/html/rfc959

**Comment by behnamben** [comment]
I also tried:

USER ubuntu
PASS ubuntu
PORT 127,0,0,1,152,193
RETR file.f

and it gave me the same error. Am I doing something wrong here?

**Comment by hfiref0x** [comment]
Out of curiosity, what you want to do? Do you writing a client, that is connecting to the ftp server?

**Comment by behnamben** [comment]
I was trying to automate these messages so I can use this as a case study for my research. However, I saw that some of the commands are never working. So I'm trying to use them manually to make them work and then add them to my tool.

The main goal is to send a different combination of commands and then extract a state machine out of the responses from the FTP server.
