### ISSUE TITLE
Error when running on 32bits machine

### ISSUE THREAD

**Issue by tylzh97** [hfiref0x/LightFTP#24]
Hello, I compile LightFTP in Ubuntu 16.04 x86, but i can't run it  correctly with hint:
**off_t is not 64 bits long**

![image](https://user-images.githubusercontent.com/24435007/187146092-e5b238bd-12ee-4cc2-85a2-208f1df724c0.png)

how could i fix it?

**Comment by UldisRinkevichs** [comment]
I was unable to reproduce this bug using latest LTS live i386 iso from [https://releases.ubuntu.com/xenial/](url) inside virtualbox
steps to build:
**sudo apt-get update**
**sudo apt-get install libgnutls28-dev libgnutls30**
cd -> to Debug directory
**make [clean**]
**make**
**./fftp**
![3](https://user-images.githubusercontent.com/39919590/187735963-259728b4-7b1d-47f3-906a-1fed3d0e7a18.png)
![2](https://user-images.githubusercontent.com/39919590/187735973-c88d8d37-45fa-4104-b362-11d682797c34.png)
![1](https://user-images.githubusercontent.com/39919590/187735974-119e0c44-0b0e-4d78-b8df-4accde6d2d5a.png)

**Comment by tylzh97** [comment]
> I was unable to reproduce this bug using latest LTS live i386 iso from [https://releases.ubuntu.com/xenial/](url) inside virtualbox steps to build: **sudo apt-get update** **sudo apt-get install libgnutls28-dev libgnutls30** cd -> to Debug directory **make clean** **make** **./fftp** ![3](https://user-images.githubusercontent.com/39919590/187735963-259728b4-7b1d-47f3-906a-1fed3d0e7a18.png) ![2](https://user-images.githubusercontent.com/39919590/187735973-c88d8d37-45fa-4104-b362-11d682797c34.png) ![1](https://user-images.githubusercontent.com/39919590/187735974-119e0c44-0b0e-4d78-b8df-4accde6d2d5a.png)
> 
> Please check your packages and build environment.

---

Based on your steps , I figured out the reason that i am using the old branch 5980ea1 of this project . 

The problem is `LightFTP/Source/Debug/subdir.mk:29`:

```shell
gcc -std=c99 -O0 -g3 -Wall -pthread -c -fmessage-length=0 -fno-ident -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
```

In `main.c:80`, there is a check `sizeof(off_t)==8`, for this reason `-D_FILE_OFFSET_BITS=64` flag is necessary. Edit subdir.mk:29 like following will fix this:

```shell
gcc -std=c99 -D_FILE_OFFSET_BITS=64 -O0 -g3 -Wall -pthread -c -fmessage-length=0 -fno-ident -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
```
