### ISSUE TITLE
Race Condition for FTP commands for which a new handler thread is created while using FileName variable

### ISSUE THREAD

**Issue by zTrix** [hfiref0x/LightFTP#25]
Hi, 

There exists a race condition for commands which creates a new thread to handle while using context->FileName, examples  such as `RETR`, `MLSD`.

Steps to reproduce:

1. login using a username such as `anonymous`
2. using `PASV` to make it passive mode
3. send `RETR` command with a existing file, to create the handler thread. Since it's passive mode, the handler thread would block there waiting for data socket connection. 
4. send `USER` command to overwrite `context->FileName`.
5. Connect the data socket, then the handler thread would use the overwritten `context->FileName` which could cause path traversal or other security issues.

This is used to create a real-world style challenge in Real World CTF 5th which just ended, sorry for notifying here a bit late.

**Comment by UldisRinkevichs** [comment]
Thank you for information. This is interesting and serious bug that will be fixed in upcoming update.

**Comment by hfiref0x** [comment]
@zTrix 

Hello,

let us know if you are willing to add anything else to your initial post. If not, then the proposed fix will be released shortly as 2.3 version.

**Comment by zTrix** [comment]
Thanks for asking. I have nothing more to add.
