### ISSUE TITLE
Failed to start server. Can not bind to address

### ISSUE THREAD

**Issue by Mirabeau2Code** [hfiref0x/LightFTP#29]
Hi

if fftp running as a user get : "Failed to start server. Can not bind to address"
(and not quit (!) when got this error)

it must be running as root to running ok

i try bind different config:
interface=0.0.0.0
#interface=192.168.0.112

why can't running as a simple user ?

**Comment by hfiref0x** [comment]
https://www.baeldung.com/linux/bind-process-privileged-port

**Comment by ruikangPeng** [comment]
@Mirabeau2Code 
Hi，
I solved this problem by modifying the fftp.conf file. Specifically, it means changing the IP and subnet mask in the fftp.conf file to the local IP and subnet mask.
Hope it can help you.

**Comment by 08183080** [comment]
you just sudo.

**Comment by UldisRinkevichs** [comment]
Closed as stale
