### ISSUE TITLE
Found an error caused by the fftp.conf file

### ISSUE THREAD

**Issue by ruikangPeng** [hfiref0x/LightFTP#32]
Hi.
I found a fatal error triggered by the fftp.conf file. The error is triggered in the following way:

1. Modify fftp.conf file: maxusers=-1
2. use. /fftp [path to fftp.conf]/fftp.conf to start the ftp service.

As shown in the following figure, LightFTP is able to start the service normally, and the maximum number of connections reaches a value that we cannot allow.
![LightFTP Server](https://github.com/hfiref0x/LightFTP/assets/104423880/da742421-1441-4462-a1ef-03d416f298d9)

 Looking forward to your reply.

**Comment by hfiref0x** [comment]
The only error I see here is an inadequate settings you made yourself. This is _your_ configuration file. What you write here is what you get.
