### ISSUE TITLE
Wrong CRC in release

### ISSUE THREAD

**Issue by greenozon** [hfiref0x/LightFTP#36]
LightFTP-2.3.1.zip  has got wrong hashes...

![image](https://github.com/user-attachments/assets/8b9e7263-42a6-4a76-a9b3-23a97c96acbe)

Expectations:  0 errors in release archives

**Comment by hfiref0x** [comment]
This file is no longer valid and wasn't updated for 3 years. Thanks for reminding about it, file will be removed.
