### ISSUE TITLE
can not overwrite a file

### ISSUE THREAD

**Issue by Denaris01** [hfiref0x/LightFTP#6]
Hello,

i run LightFTP on debian 8. I can not overwrite a file. i must first delete the file and then i can upload the same, new file again. Testet whit Totalcommander and Filezilla as client.

**Comment by hfiref0x** [comment]
Hello, thanks for reporting this bug.

**Comment by Denaris01** [comment]
Hello, thanks for the fast bugfixing xD
Now all works fine. This is now the BEST ftp-server for linux. Different user whit different locked homes and aktiv/passiv mode easy to configure. And i can assign a IP form the root to the ftp-server.
A SSL-option (sftp) would be nice as last feature, but not required.

Thanks for this,
Christian
