### ISSUE TITLE
Server stops working whit many, smal files

### ISSUE THREAD

**Issue by Denaris01** [hfiref0x/LightFTP#7]
Hello,

i run debian 9 whit LightFTP and when a client uploads many, smal files the ftp-server exit's whit no error. then i must restart the server and he is working again for a short time. If the client has more connections at the same time, the crash are earlier.
Can you add a option to disable the logfile? i thing here are the problem.

`[ftpconfig]
port=5297
maxusers=99
interface=188.68.xx.xx
external_ip=188.68.xx.xx
local_mask=255.255.252.0
minport=6000
maxport=6999
logfilepath=fftplog

[kebitv]
pswd=xxxxxxxxx
accs=admin
root=/home/cube/kebitv/McMyAdmin/Minecraft`

**Comment by Denaris01** [comment]
I have testet a bit and the LightFTP (on debian 8 +9) stops only if the Client are Filezilla. Whit TotalCommander, WinSCP etc. are no Problems.

**Comment by hfiref0x** [comment]
Hello,
which version of filezilla you use? Can you give more system information.

**Comment by hfiref0x** [comment]
Ability to disable log added in 8b518f1500a115986bef4e44fbc2262d6f06d131 commit. Now if logfilepath is not set logging will be disabled. The bug with Filezilla is not reproducible here. Closed until further issue info available.
